#ifndef DEMO_BOARD_H
#define DEMO_BOARD_H
#include "driver/gpio.h"
#define DEMO_RELAY_GPIO GPIO_NUM_4
#define DEMO_PLUG_GPIO GPIO_NUM_5
#define DEMO_FAN_PWM_GPIO GPIO_NUM_6
#define DEMO_CONTACT_GPIO GPIO_NUM_7
#define DEMO_LIGHT_GPIO GPIO_NUM_8
#define DEMO_BUTTON_GPIO GPIO_NUM_9
#define DEMO_DIMMER_PWM_GPIO GPIO_NUM_10
#endif
